services:
  guesslang-worker:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "8787:8787"
    environment:
      - NODE_ENV=production
      - PORT=8787
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:8787/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - guesslang-network

networks:
  guesslang-network:
    driver: bridge
