services:
  guesslang-worker-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - "8787:8787"
    environment:
      - NODE_ENV=development
      - PORT=8787
    volumes:
      # Mount source code for hot reload
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./tsconfig.json:/app/tsconfig.json
      - ./vite.config.ts:/app/vite.config.ts
      - ./node_modules/@vscode/vscode-languagedetection:/app/node_modules/@vscode/vscode-languagedetection
    command: ["sh", "-c", "pnpm run build && node dist/server.js"]
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:8787/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - guesslang-dev-network

networks:
  guesslang-dev-network:
    driver: bridge
