name = "guesslang"
main = "src/index.ts"
compatibility_date = "2023-12-01"
compatibility_flags = [ "nodejs_compat" ]
minify = true
rules = [
  { type = "Data", globs = ["**/*.bin"], fallthrough = true }
]

# [vars]
# MY_VARIABLE = "production_value"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""
